//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplesToApples.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplesToApples.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Absurd] - (ridiculous, senseless, foolish) 
        ///[Abundant] - (plentiful, ample, numerous) 
        ///[Addictive] - (obsessive, consuming, captivating) 
        ///[Adorable] - (lovable, charming, delightful) 
        ///[Adorable] - (lovable, cute) 
        ///[Aged] - (old, ancient, mature) 
        ///[Amazing] - (astonishing, surprising, wonderful) 
        ///[Amazing] - (surprising, wonderful) 
        ///[American] - (U.S. Citizen, Yankee, Apple Pie) 
        ///[Ancient] - (elderly, old, antique) 
        ///[Animated] - (lively, exuberant, spirited) 
        ///[Annoying] - (irritating, bothersome, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GreenApples {
            get {
                return ResourceManager.GetString("GreenApples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A Bad Haircut] - The perfect start to a bad hair day. 
        ///[A Bakery] - Some bakers start work at 3:00 in the morning, so breads and donuts are fresh for  breakfast. 
        ///[A Broken Leg] - I was riding my bike when I hit this big rock . . . 
        ///[A Bull Fight] - Also known as &quot;la fiesta brava&quot; (the brave festival).  A whole lot of bull.. 
        ///[A Cabin In The Woods] - Henry David Thoreau went to Walden Pond for two years.  All we&apos;re asking for is one lousy weekend! 
        ///[A Can Of Worms] - Now you&apos;ve opened it. 
        ///[A Car Cra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RedApples {
            get {
                return ResourceManager.GetString("RedApples", resourceCulture);
            }
        }
    }
}
